const RAW_NICKNAME_PRESETS = [
  'American Sniper',
  'Michael Jordan',
  'Muhammad Ali',
  'Fore Father',
  'Tom Brady',
  'Pencil Pro',
  'Fairway to Heaven',
  'Thaddeus Gonnaplay',
  'Seymour Fairways',
  'Vladimir Puttin',
  'Crypto Bro',
  'Dalai Lama',
  'Gunga Galunga',
  'Leech',
  'Hosel Rocket Scientist',
  'Worm Burner',
  'Arsonist',
  'Atomic Wedgie',
  'Jabba the Putt',
  'Underwear Bomber',
  'Big-Tuna',
  'Roomba',
  'Beaver Pelt',
  'Windex',
  'Mulligan Medic',
  'Will Hunting',
  'Scorecard Custodian',
  'Carl Spackler',
  'Houdini',
  'Witness Protection',
  'Kim K',
  'Drawshank Redemption',
  'Poulter-geist',
  'Bounce-Back Refund',
  'Round Rebooter',
  'Do-Over Dealer',
  'Apology Department',
  'Back Nine Butcher',
  'Clutch King',
  'Pacemaker',
  'Final Putt Coroner',
  'Parking Lot Undertaker',
  'Last Hole Taxman',
  'Lights-Out Closer',
  'Card Killer',
  'Last-Hole Collector',
  'Handicap Hustler',
  'Handicap Parking',
  'Net Par Party',
  'Scorecard Forger',
  'Popsie Plus Pirate',
  'Bogey Man',
  'Loose Wire',
  'Christopher Columbus',
  'Little Richard',
  'Captain Hook',
  'Tsar Bomba',
  'My Husband Golfs too',
  'Shank Alert',
  'Best Double Bogey Putter',
  'Cart Path Union Worker',
  'Hazardous Material',
  'OB Wan Kenobi',
  'Footwege Frank',
  'Frosty the Snowman',
  'Scuba Gear',
  "How's My Driving? Call 1-800-FUCK-OFF",
  'Purse Clutcher',
  'Put Me Down for a 5',
  'Tin Cup',
  'She has Caddie Issues',
  'Bunker Buster',
  'Shanks Fornuttin',
  'Meatloaf',
  'Penile Detention Center',
  'Safety Golf Warden',
  'Department of Golf Efficiency',
  'Highway Patrol',
  "Daisy (Some Daisys Here, Some Days He's Not)",
  'Cameo Appearance',
  'Fairweather Fan',
  'Ball and Chain',
  'Tee Time Ghost',
  'Guest List',
  'Day Pass',
  'Surprise Appearance',
  'Calendar Conflict',
  'Blue Collar Golfer',
  'Steady Eddy',
  'Cool As a Cucumber',
  'Quiet Money',
  'Surgeon',
  'Tattoo Artist',
  'Bomb Squad',
] as const;

export function normalizeNicknamePreset(value: string): string {
  const trimmed = value.trim();
  if (!trimmed) return '';
  return trimmed.replace(/^the\s+/i, '');
}

export const NICKNAME_PRESETS = Array.from(
  new Set(RAW_NICKNAME_PRESETS.map((value) => normalizeNicknamePreset(value)).filter((value) => value.length > 0)),
).sort((a, b) => a.localeCompare(b));
